-- Curated seed catalog in the spirit of the well-known "Blind 75" list.
-- Premium-locked LeetCode problems (e.g. Meeting Rooms, Alien Dictionary, Graph Valid Tree,
-- Encode and Decode Strings, Number of Connected Components) are excluded since free users
-- can't open them anyway. 74 problems, only well-known/free ones included for data accuracy.
insert into public.problems (id, slug, title, difficulty, topics, url) values
  (1, 'two-sum', 'Two Sum', 'Easy', '{Array,"Hash Table"}', 'https://leetcode.com/problems/two-sum'),
  (2, 'add-two-numbers', 'Add Two Numbers', 'Medium', '{"Linked List",Math}', 'https://leetcode.com/problems/add-two-numbers'),
  (3, 'longest-substring-without-repeating-characters', 'Longest Substring Without Repeating Characters', 'Medium', '{"Hash Table",String,"Sliding Window"}', 'https://leetcode.com/problems/longest-substring-without-repeating-characters'),
  (5, 'longest-palindromic-substring', 'Longest Palindromic Substring', 'Medium', '{String,DP}', 'https://leetcode.com/problems/longest-palindromic-substring'),
  (11, 'container-with-most-water', 'Container With Most Water', 'Medium', '{Array,"Two Pointers"}', 'https://leetcode.com/problems/container-with-most-water'),
  (15, '3sum', '3Sum', 'Medium', '{Array,"Two Pointers"}', 'https://leetcode.com/problems/3sum'),
  (19, 'remove-nth-node-from-end-of-list', 'Remove Nth Node From End of List', 'Medium', '{"Linked List","Two Pointers"}', 'https://leetcode.com/problems/remove-nth-node-from-end-of-list'),
  (20, 'valid-parentheses', 'Valid Parentheses', 'Easy', '{String,Stack}', 'https://leetcode.com/problems/valid-parentheses'),
  (21, 'merge-two-sorted-lists', 'Merge Two Sorted Lists', 'Easy', '{"Linked List"}', 'https://leetcode.com/problems/merge-two-sorted-lists'),
  (23, 'merge-k-sorted-lists', 'Merge k Sorted Lists', 'Hard', '{"Linked List",Heap}', 'https://leetcode.com/problems/merge-k-sorted-lists'),
  (33, 'search-in-rotated-sorted-array', 'Search in Rotated Sorted Array', 'Medium', '{Array,"Binary Search"}', 'https://leetcode.com/problems/search-in-rotated-sorted-array'),
  (39, 'combination-sum', 'Combination Sum', 'Medium', '{Backtracking}', 'https://leetcode.com/problems/combination-sum'),
  (42, 'trapping-rain-water', 'Trapping Rain Water', 'Hard', '{Array,"Two Pointers",DP}', 'https://leetcode.com/problems/trapping-rain-water'),
  (46, 'permutations', 'Permutations', 'Medium', '{Backtracking}', 'https://leetcode.com/problems/permutations'),
  (48, 'rotate-image', 'Rotate Image', 'Medium', '{Array}', 'https://leetcode.com/problems/rotate-image'),
  (49, 'group-anagrams', 'Group Anagrams', 'Medium', '{"Hash Table",String}', 'https://leetcode.com/problems/group-anagrams'),
  (53, 'maximum-subarray', 'Maximum Subarray', 'Medium', '{Array,DP}', 'https://leetcode.com/problems/maximum-subarray'),
  (54, 'spiral-matrix', 'Spiral Matrix', 'Medium', '{Array}', 'https://leetcode.com/problems/spiral-matrix'),
  (55, 'jump-game', 'Jump Game', 'Medium', '{Array,Greedy,DP}', 'https://leetcode.com/problems/jump-game'),
  (56, 'merge-intervals', 'Merge Intervals', 'Medium', '{Array}', 'https://leetcode.com/problems/merge-intervals'),
  (57, 'insert-interval', 'Insert Interval', 'Medium', '{Array}', 'https://leetcode.com/problems/insert-interval'),
  (62, 'unique-paths', 'Unique Paths', 'Medium', '{DP}', 'https://leetcode.com/problems/unique-paths'),
  (70, 'climbing-stairs', 'Climbing Stairs', 'Easy', '{DP}', 'https://leetcode.com/problems/climbing-stairs'),
  (73, 'set-matrix-zeroes', 'Set Matrix Zeroes', 'Medium', '{Array}', 'https://leetcode.com/problems/set-matrix-zeroes'),
  (76, 'minimum-window-substring', 'Minimum Window Substring', 'Hard', '{String,"Sliding Window"}', 'https://leetcode.com/problems/minimum-window-substring'),
  (79, 'word-search', 'Word Search', 'Medium', '{Backtracking}', 'https://leetcode.com/problems/word-search'),
  (91, 'decode-ways', 'Decode Ways', 'Medium', '{DP,String}', 'https://leetcode.com/problems/decode-ways'),
  (98, 'validate-binary-search-tree', 'Validate Binary Search Tree', 'Medium', '{Tree}', 'https://leetcode.com/problems/validate-binary-search-tree'),
  (100, 'same-tree', 'Same Tree', 'Easy', '{Tree}', 'https://leetcode.com/problems/same-tree'),
  (102, 'binary-tree-level-order-traversal', 'Binary Tree Level Order Traversal', 'Medium', '{Tree,BFS}', 'https://leetcode.com/problems/binary-tree-level-order-traversal'),
  (104, 'maximum-depth-of-binary-tree', 'Maximum Depth of Binary Tree', 'Easy', '{Tree}', 'https://leetcode.com/problems/maximum-depth-of-binary-tree'),
  (105, 'construct-binary-tree-from-preorder-and-inorder-traversal', 'Construct Binary Tree from Preorder and Inorder Traversal', 'Medium', '{Tree}', 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal'),
  (121, 'best-time-to-buy-and-sell-stock', 'Best Time to Buy and Sell Stock', 'Easy', '{Array,DP}', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock'),
  (124, 'binary-tree-maximum-path-sum', 'Binary Tree Maximum Path Sum', 'Hard', '{Tree}', 'https://leetcode.com/problems/binary-tree-maximum-path-sum'),
  (125, 'valid-palindrome', 'Valid Palindrome', 'Easy', '{String,"Two Pointers"}', 'https://leetcode.com/problems/valid-palindrome'),
  (128, 'longest-consecutive-sequence', 'Longest Consecutive Sequence', 'Medium', '{Array,"Union Find"}', 'https://leetcode.com/problems/longest-consecutive-sequence'),
  (133, 'clone-graph', 'Clone Graph', 'Medium', '{Graph,DFS,BFS}', 'https://leetcode.com/problems/clone-graph'),
  (139, 'word-break', 'Word Break', 'Medium', '{DP,String}', 'https://leetcode.com/problems/word-break'),
  (141, 'linked-list-cycle', 'Linked List Cycle', 'Easy', '{"Linked List"}', 'https://leetcode.com/problems/linked-list-cycle'),
  (143, 'reorder-list', 'Reorder List', 'Medium', '{"Linked List"}', 'https://leetcode.com/problems/reorder-list'),
  (146, 'lru-cache', 'LRU Cache', 'Medium', '{Design,"Hash Table"}', 'https://leetcode.com/problems/lru-cache'),
  (152, 'maximum-product-subarray', 'Maximum Product Subarray', 'Medium', '{Array,DP}', 'https://leetcode.com/problems/maximum-product-subarray'),
  (153, 'find-minimum-in-rotated-sorted-array', 'Find Minimum in Rotated Sorted Array', 'Medium', '{Array,"Binary Search"}', 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array'),
  (190, 'reverse-bits', 'Reverse Bits', 'Easy', '{"Bit Manipulation"}', 'https://leetcode.com/problems/reverse-bits'),
  (191, 'number-of-1-bits', 'Number of 1 Bits', 'Easy', '{"Bit Manipulation"}', 'https://leetcode.com/problems/number-of-1-bits'),
  (198, 'house-robber', 'House Robber', 'Medium', '{DP}', 'https://leetcode.com/problems/house-robber'),
  (200, 'number-of-islands', 'Number of Islands', 'Medium', '{Graph,DFS,BFS}', 'https://leetcode.com/problems/number-of-islands'),
  (206, 'reverse-linked-list', 'Reverse Linked List', 'Easy', '{"Linked List"}', 'https://leetcode.com/problems/reverse-linked-list'),
  (207, 'course-schedule', 'Course Schedule', 'Medium', '{Graph,"Topological Sort"}', 'https://leetcode.com/problems/course-schedule'),
  (208, 'implement-trie-prefix-tree', 'Implement Trie (Prefix Tree)', 'Medium', '{Trie,Design}', 'https://leetcode.com/problems/implement-trie-prefix-tree'),
  (211, 'design-add-and-search-words-data-structure', 'Design Add and Search Words Data Structure', 'Medium', '{Trie,Design}', 'https://leetcode.com/problems/design-add-and-search-words-data-structure'),
  (212, 'word-search-ii', 'Word Search II', 'Hard', '{Trie,Backtracking}', 'https://leetcode.com/problems/word-search-ii'),
  (213, 'house-robber-ii', 'House Robber II', 'Medium', '{DP}', 'https://leetcode.com/problems/house-robber-ii'),
  (215, 'kth-largest-element-in-an-array', 'Kth Largest Element in an Array', 'Medium', '{Heap,Sort}', 'https://leetcode.com/problems/kth-largest-element-in-an-array'),
  (217, 'contains-duplicate', 'Contains Duplicate', 'Easy', '{Array,"Hash Table"}', 'https://leetcode.com/problems/contains-duplicate'),
  (226, 'invert-binary-tree', 'Invert Binary Tree', 'Easy', '{Tree}', 'https://leetcode.com/problems/invert-binary-tree'),
  (230, 'kth-smallest-element-in-a-bst', 'Kth Smallest Element in a BST', 'Medium', '{Tree}', 'https://leetcode.com/problems/kth-smallest-element-in-a-bst'),
  (235, 'lowest-common-ancestor-of-a-binary-search-tree', 'Lowest Common Ancestor of a Binary Search Tree', 'Medium', '{Tree}', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree'),
  (238, 'product-of-array-except-self', 'Product of Array Except Self', 'Medium', '{Array}', 'https://leetcode.com/problems/product-of-array-except-self'),
  (239, 'sliding-window-maximum', 'Sliding Window Maximum', 'Hard', '{Array,Heap,"Sliding Window"}', 'https://leetcode.com/problems/sliding-window-maximum'),
  (242, 'valid-anagram', 'Valid Anagram', 'Easy', '{"Hash Table",String}', 'https://leetcode.com/problems/valid-anagram'),
  (268, 'missing-number', 'Missing Number', 'Easy', '{Array,"Bit Manipulation"}', 'https://leetcode.com/problems/missing-number'),
  (295, 'find-median-from-data-stream', 'Find Median from Data Stream', 'Hard', '{Heap,Design}', 'https://leetcode.com/problems/find-median-from-data-stream'),
  (297, 'serialize-and-deserialize-binary-tree', 'Serialize and Deserialize Binary Tree', 'Hard', '{Tree,Design}', 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree'),
  (300, 'longest-increasing-subsequence', 'Longest Increasing Subsequence', 'Medium', '{DP,"Binary Search"}', 'https://leetcode.com/problems/longest-increasing-subsequence'),
  (322, 'coin-change', 'Coin Change', 'Medium', '{DP}', 'https://leetcode.com/problems/coin-change'),
  (338, 'counting-bits', 'Counting Bits', 'Easy', '{DP,"Bit Manipulation"}', 'https://leetcode.com/problems/counting-bits'),
  (347, 'top-k-frequent-elements', 'Top K Frequent Elements', 'Medium', '{Heap,"Hash Table"}', 'https://leetcode.com/problems/top-k-frequent-elements'),
  (371, 'sum-of-two-integers', 'Sum of Two Integers', 'Medium', '{"Bit Manipulation"}', 'https://leetcode.com/problems/sum-of-two-integers'),
  (417, 'pacific-atlantic-water-flow', 'Pacific Atlantic Water Flow', 'Medium', '{Graph,DFS}', 'https://leetcode.com/problems/pacific-atlantic-water-flow'),
  (424, 'longest-repeating-character-replacement', 'Longest Repeating Character Replacement', 'Medium', '{String,"Sliding Window"}', 'https://leetcode.com/problems/longest-repeating-character-replacement'),
  (435, 'non-overlapping-intervals', 'Non-overlapping Intervals', 'Medium', '{Array,Greedy}', 'https://leetcode.com/problems/non-overlapping-intervals'),
  (572, 'subtree-of-another-tree', 'Subtree of Another Tree', 'Easy', '{Tree}', 'https://leetcode.com/problems/subtree-of-another-tree'),
  (647, 'palindromic-substrings', 'Palindromic Substrings', 'Medium', '{String,DP}', 'https://leetcode.com/problems/palindromic-substrings');
